In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import sklearn.tree

In [47]:
data=pd.read_csv('Iris.csv')

In [48]:
data['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [49]:
data.groupby(['Species']).mean()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,25.5,5.006,3.418,1.464,0.244
Iris-versicolor,75.5,5.936,2.770,4.260,1.326
Iris-virginica,125.5,6.588,2.974,5.552,2.026

In [50]:
data=data.drop(['Id'],axis=1)

In [51]:
y=data['Species']

In [52]:
data=data.drop(['Species'],axis=1)

In [61]:
data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
5              5.4           3.9            1.7           0.4
6              4.6           3.4            1.4           0.3
7              5.0           3.4            1.5           0.2
8              4.4           2.9            1.4           0.2
9              4.9           3.1            1.5           0.1
10             5.4           3.7            1.5           0.2
11             4.8           3.4            1.6           0.2
12             4.8           3.0            1.4           0.1
13             4.3           3.0            1.1           0.1
14             5.8           4.0            1.2           0.2
15             5.7           4.4            1.5           0.4
16             5.4           3.9            1.3           0.4
17             5.1           3.5            1.4           0.3
18             5.7           3.8            1.7           0.3
19             5.1           3.8            1.5           0.3
20             5.4           3.4            1.7           0.2
21             5.1           3.7            1.5           0.4
22             4.6           3.6            1.0           0.2
23             5.1           3.3            1.7           0.5
24             4.8           3.4            1.9           0.2
25             5.0           3.0            1.6           0.2
26             5.0           3.4            1.6           0.4
27             5.2           3.5            1.5           0.2
28             5.2           3.4            1.4           0.2
29             4.7           3.2            1.6           0.2
..             ...           ...            ...           ...
120            6.9           3.2            5.7           2.3
121            5.6           2.8            4.9           2.0
122            7.7           2.8            6.7           2.0
123            6.3           2.7            4.9           1.8
124            6.7           3.3            5.7           2.1
125            7.2           3.2            6.0           1.8
126            6.2           2.8            4.8           1.8
127            6.1           3.0            4.9           1.8
128            6.4           2.8            5.6           2.1
129            7.2           3.0            5.8           1.6
130            7.4           2.8            6.1           1.9
131            7.9           3.8            6.4           2.0
132            6.4           2.8            5.6           2.2
133            6.3           2.8            5.1           1.5
134            6.1           2.6            5.6           1.4
135            7.7           3.0            6.1           2.3
136            6.3           3.4            5.6           2.4
137            6.4           3.1            5.5           1.8
138            6.0           3.0            4.8           1.8
139            6.9           3.1            5.4           2.1
140            6.7           3.1            5.6           2.4
141            6.9           3.1            5.1           2.3
142            5.8           2.7            5.1           1.9
143            6.8           3.2            5.9           2.3
144            6.7           3.3            5.7           2.5
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [53]:
x=data

In [54]:
x_train,x_teat,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.2)

In [55]:
clf_gini=sklearn.tree.DecisionTreeClassifier(criterion='gini',random_state=100,max_depth=3,min_samples_leaf=5)

In [56]:
clf_gini.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [57]:
clf_gini.score(x_train,y_train)

0.9583333333333334

In [58]:
clf=clf_gini.fit(x_train,y_train)

In [59]:
sklearn.tree.export_graphviz(clf,out_file='tree.dot')
#convert tree.dot to png

In [143]:
data=pd.read_csv('traintitanic.csv')

In [144]:
data.groupby(['Survived']).mean()

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [145]:
data=data.drop(["PassengerId","Fare","Ticket","Name","Cabin"],axis=1)

In [146]:
data=data.join(pd.get_dummies(data['Sex']))
data=data.drop(["Sex"],axis=1)
data=data.join(pd.get_dummies(data['Embarked']))
data=data.drop(["Embarked"],axis=1)

In [147]:
data=data.drop(['female'],axis=1)

In [148]:
data

     Survived  Pclass   Age  SibSp  Parch  male  C  Q  S
0           0       3  22.0      1      0     1  0  0  1
1           1       1  38.0      1      0     0  1  0  0
2           1       3  26.0      0      0     0  0  0  1
3           1       1  35.0      1      0     0  0  0  1
4           0       3  35.0      0      0     1  0  0  1
5           0       3   NaN      0      0     1  0  1  0
6           0       1  54.0      0      0     1  0  0  1
7           0       3   2.0      3      1     1  0  0  1
8           1       3  27.0      0      2     0  0  0  1
9           1       2  14.0      1      0     0  1  0  0
10          1       3   4.0      1      1     0  0  0  1
11          1       1  58.0      0      0     0  0  0  1
12          0       3  20.0      0      0     1  0  0  1
13          0       3  39.0      1      5     1  0  0  1
14          0       3  14.0      0      0     0  0  0  1
15          1       2  55.0      0      0     0  0  0  1
16          0       3   2.0      4      1     1  0  1  0
17          1       2   NaN      0      0     1  0  0  1
18          0       3  31.0      1      0     0  0  0  1
19          1       3   NaN      0      0     0  1  0  0
20          0       2  35.0      0      0     1  0  0  1
21          1       2  34.0      0      0     1  0  0  1
22          1       3  15.0      0      0     0  0  1  0
23          1       1  28.0      0      0     1  0  0  1
24          0       3   8.0      3      1     0  0  0  1
25          1       3  38.0      1      5     0  0  0  1
26          0       3   NaN      0      0     1  1  0  0
27          0       1  19.0      3      2     1  0  0  1
28          1       3   NaN      0      0     0  0  1  0
29          0       3   NaN      0      0     1  0  0  1
..        ...     ...   ...    ...    ...   ... .. .. ..
861         0       2  21.0      1      0     1  0  0  1
862         1       1  48.0      0      0     0  0  0  1
863         0       3   NaN      8      2     0  0  0  1
864         0       2  24.0      0      0     1  0  0  1
865         1       2  42.0      0      0     0  0  0  1
866         1       2  27.0      1      0     0  1  0  0
867         0       1  31.0      0      0     1  0  0  1
868         0       3   NaN      0      0     1  0  0  1
869         1       3   4.0      1      1     1  0  0  1
870         0       3  26.0      0      0     1  0  0  1
871         1       1  47.0      1      1     0  0  0  1
872         0       1  33.0      0      0     1  0  0  1
873         0       3  47.0      0      0     1  0  0  1
874         1       2  28.0      1      0     0  1  0  0
875         1       3  15.0      0      0     0  1  0  0
876         0       3  20.0      0      0     1  0  0  1
877         0       3  19.0      0      0     1  0  0  1
878         0       3   NaN      0      0     1  0  0  1
879         1       1  56.0      0      1     0  1  0  0
880         1       2  25.0      0      1     0  0  0  1
881         0       3  33.0      0      0     1  0  0  1
882         0       3  22.0      0      0     0  0  0  1
883         0       2  28.0      0      0     1  0  0  1
884         0       3  25.0      0      0     1  0  0  1
885         0       3  39.0      0      5     0  0  1  0
886         0       2  27.0      0      0     1  0  0  1
887         1       1  19.0      0      0     0  0  0  1
888         0       3   NaN      1      2     0  0  0  1
889         1       1  26.0      0      0     1  1  0  0
890         0       3  32.0      0      0     1  0  1  0

[891 rows x 9 columns]

In [158]:
data=data.dropna()
y=data["Survived"]
data=data.drop(['Survived'],axis=1)

In [160]:
x=data
x

     Pclass   Age  SibSp  Parch  male  C  Q  S
0         3  22.0      1      0     1  0  0  1
1         1  38.0      1      0     0  1  0  0
2         3  26.0      0      0     0  0  0  1
3         1  35.0      1      0     0  0  0  1
4         3  35.0      0      0     1  0  0  1
6         1  54.0      0      0     1  0  0  1
7         3   2.0      3      1     1  0  0  1
8         3  27.0      0      2     0  0  0  1
9         2  14.0      1      0     0  1  0  0
10        3   4.0      1      1     0  0  0  1
11        1  58.0      0      0     0  0  0  1
12        3  20.0      0      0     1  0  0  1
13        3  39.0      1      5     1  0  0  1
14        3  14.0      0      0     0  0  0  1
15        2  55.0      0      0     0  0  0  1
16        3   2.0      4      1     1  0  1  0
18        3  31.0      1      0     0  0  0  1
20        2  35.0      0      0     1  0  0  1
21        2  34.0      0      0     1  0  0  1
22        3  15.0      0      0     0  0  1  0
23        1  28.0      0      0     1  0  0  1
24        3   8.0      3      1     0  0  0  1
25        3  38.0      1      5     0  0  0  1
27        1  19.0      3      2     1  0  0  1
30        1  40.0      0      0     1  1  0  0
33        2  66.0      0      0     1  0  0  1
34        1  28.0      1      0     1  1  0  0
35        1  42.0      1      0     1  0  0  1
37        3  21.0      0      0     1  0  0  1
38        3  18.0      2      0     0  0  0  1
..      ...   ...    ...    ...   ... .. .. ..
856       1  45.0      1      1     0  0  0  1
857       1  51.0      0      0     1  0  0  1
858       3  24.0      0      3     0  1  0  0
860       3  41.0      2      0     1  0  0  1
861       2  21.0      1      0     1  0  0  1
862       1  48.0      0      0     0  0  0  1
864       2  24.0      0      0     1  0  0  1
865       2  42.0      0      0     0  0  0  1
866       2  27.0      1      0     0  1  0  0
867       1  31.0      0      0     1  0  0  1
869       3   4.0      1      1     1  0  0  1
870       3  26.0      0      0     1  0  0  1
871       1  47.0      1      1     0  0  0  1
872       1  33.0      0      0     1  0  0  1
873       3  47.0      0      0     1  0  0  1
874       2  28.0      1      0     0  1  0  0
875       3  15.0      0      0     0  1  0  0
876       3  20.0      0      0     1  0  0  1
877       3  19.0      0      0     1  0  0  1
879       1  56.0      0      1     0  1  0  0
880       2  25.0      0      1     0  0  0  1
881       3  33.0      0      0     1  0  0  1
882       3  22.0      0      0     0  0  0  1
883       2  28.0      0      0     1  0  0  1
884       3  25.0      0      0     1  0  0  1
885       3  39.0      0      5     0  0  1  0
886       2  27.0      0      0     1  0  0  1
887       1  19.0      0      0     0  0  0  1
889       1  26.0      0      0     1  1  0  0
890       3  32.0      0      0     1  0  1  0

[714 rows x 8 columns]

In [161]:
x_train,x_teat,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.2)
clf_gini=sklearn.tree.DecisionTreeClassifier(criterion='gini',random_state=100,max_depth=3,min_samples_leaf=5)

In [162]:
clf_gini.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [163]:
clf_gini.score(x_train,y_train)

0.819614711033275

In [164]:
clf=clf_gini.fit(x_train,y_train)
sklearn.tree.export_graphviz(clf,out_file='treetitanic.dot')